FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src/common ./common/
COPY resources ./resources

COPY src/server ./server/

CMD ["uvicorn", "server.server:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]

