#This workflow will run unit tests

name: CI with commit checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2
        # Setup which version of Python to use
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        #install required packages
      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Run the tests.
      - name: Run tests
        run: python test/unit/run.py